# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# tmp.py
# Created on: 2017-10-24 11:54:52.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: tmp <Input_Roads_Data> <Travel_Time_Field> <Priority_field> <Snap_Raster> <Output_Rasterized_Roads> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_Roads_Data = arcpy.GetParameterAsText(0)

Travel_Time_Field = arcpy.GetParameterAsText(1)
if Travel_Time_Field == '#' or not Travel_Time_Field:
    Travel_Time_Field = "TravTime" # provide a default value if unspecified

Priority_field = arcpy.GetParameterAsText(2)
if Priority_field == '#' or not Priority_field:
    Priority_field = "Speed_upd" # provide a default value if unspecified

Snap_Raster = arcpy.GetParameterAsText(3)
if Snap_Raster == '#' or not Snap_Raster:
    Snap_Raster = "H:\\Backups\\DCR_Work_DellD\\ConsVision_VulnMod\\DataConsolidation\\nlcdVA_albers.gdb\\nlcd2011_imp5" # provide a default value if unspecified

Output_Rasterized_Roads = arcpy.GetParameterAsText(4)

# Local variables:

# Process: Polyline to Raster
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = Snap Raster
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = Snap Raster
tempEnvironment2 = arcpy.env.mask
arcpy.env.mask = Snap Raster
arcpy.PolylineToRaster_conversion(Input_Roads_Data, Travel_Time_Field, Output_Rasterized_Roads, "MAXIMUM_LENGTH", Priority_field, Snap_Raster)
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1
arcpy.env.mask = tempEnvironment2

